package io.flutter.plugins

import androidx.annotation.Keep
import io.flutter.embedding.engine.FlutterEngine

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
object GeneratedPluginRegistrant {
    private const val TAG = "GeneratedPluginRegistrant"
    fun registerWith(@NonNull flutterEngine: FlutterEngine?) {}
}